name: gumby
version: '0.0.0.2'
synopsis: Mr. Gumby---a stupid slack bot.
category: Network
author: Konrad Gądek
maintainer: kgadek@gmail.com
copyright: (c) 2017 Konrad Gądek
license: MPL-2.0


dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - autoexporter
    - aeson
    - neat-interpolation
    - lens
    - bytestring
    - text
    - wreq
    - websockets
    - uri-bytestring

executables:
  gumby:
    main: Main.hs
    source-dirs: app
    dependencies:
      - gumby
      - lens
      - aeson
      - wuss
      - websockets
      - wreq
      - uri-bytestring
      - text
      - bytestring

tests:
  gumby-test:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - gumby
      - aeson
      - hspec
      - hspec-expectations
      - neat-interpolation
      - lens
      - bytestring
      - text
