resolver: lts-9.6

packages:
  - '.'

flags: {}

extra-package-dbs: []

docker:
  enable: true
  repo: fpco/stack-build

image:
  containers:
    - base: "fpco/ubuntu-with-libgmp:latest"
      name: "kgadek"
      executables:
        - gumby
      entrypoints:
        - gumby
