resolver: lts-10.3

packages:
  - '.'

flags: {}

extra-package-dbs: []

ghc-options:
  "$locals": -Werror=missing-fields

docker:
  enable: true
  repo: fpco/stack-build

image:
  containers:
    - base: "fpco/ubuntu-with-libgmp:latest"
      name: "kgadek"
      executables:
        - gumby
      entrypoints:
        - gumby
